### Send POST request with json body
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "email": "111@gmail.com",
  "password": "content"
}

### Send POST request with json body
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "111@gmail.com",
  "password": "content"
}

### GET request with a header
GET http://localhost:8080/users/me
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiMTExQGdtYWlsLmNvbSIsImlhdCI6MTY5OTYyNTgwMSwiZXhwIjoxNjk5NjI2NDAxfQ.KhsMxxfuENMnaUTZS4XAOC8akl8yB-ZfIOGQZLIe_M0
