### Send POST request with json body
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "email": "111@gmail.com",
  "password": "content"
}

### Send POST request with json body
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "111@gmail.com",
  "password": "content"
}

### GET request with a header
GET http://localhost:8080/users/me
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiMTExQGdtYWlsLmNvbSIsImlhdCI6MTcwMDkwNzczNywiZXhwIjoxNzAwOTA4MzM3fQ.7_HQwiwIP2FNoOwixwvSjc3VZd6NgkiN4gNuV3VFJhI

### Send POST request with json body
POST http://localhost:8080/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiMTExQGdtYWlsLmNvbSIsImlhdCI6MTcwMDkxMDM1MiwiZXhwIjoxNzAwOTEwOTUyfQ.f86fqJH25q75pe2BdHIJ7lcy8KulMKUkL3i_toLd_6U

{
  "title": "title 2",
  "description": "description 2",
  "url": "www.google.com"
}

### GET request with a header
GET http://localhost:8080/notes
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiMTExQGdtYWlsLmNvbSIsImlhdCI6MTcwMDkxMTg2OCwiZXhwIjoxNzAwOTEyNDY4fQ.RbnyZ7FEcHMt1z_oQYGro3DGMAxrfAEXL4vIBUn-cZE

### Send PATCH request with json body
PATCH http://localhost:8080/notes/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiMTExQGdtYWlsLmNvbSIsImlhdCI6MTcwMDkxMTM2MiwiZXhwIjoxNzAwOTExOTYyfQ.43139Nstuf0NGBvyJ8WAw4Ni-kM_rGYehXXhvqb6ZkI

{
  "title": "Updated Title",
  "description": "Updated Description",
  "url": "www.updated-url.com"
}

### Send DELETE request
DELETE http://localhost:8080/notes?id=2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiMTExQGdtYWlsLmNvbSIsImlhdCI6MTcwMDkxMjE2OSwiZXhwIjoxNzAwOTEyNzY5fQ.yN24fDyDrpq_w8lc7a81YsLv7I5DwwkjV7A7FXZ_aSw
